In [3]:
import pandas as pd
import numpy as np

In [40]:
df = pd.read_csv('../Data/Spotify_Youtube.csv')

In [21]:
df.head(2)

,Unnamed: 0,Artist,Url_spotify,Track,Album,Album_type,Uri,Danceability,Energy,Key,...,Url_youtube,Title,Channel,Views,Likes,Comments,Description,Licensed,official_video,Stream
0,0,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Feel Good Inc.,Demon Days,album,spotify:track:0d28khcov6AiegSCpG5TuT,0.818,0.705,6.0,...,https://www.youtube.com/watch?v=HyHNuVaZJ-k,Gorillaz - Feel Good Inc. (Official Video),Gorillaz,693555221.0,6220896.0,169907.0,Official HD Video for Gorillaz' fantastic trac...,True,True,1.040235e+09
1,1,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Rhinestone Eyes,Plastic Beach,album,spotify:track:1foMv2HQwfQ2vntFf9HFeG,0.676,0.703,8.0,...,https://www.youtube.com/watch?v=yYDmaexVHic,Gorillaz - Rhinestone Eyes [Storyboard Film] (...,Gorillaz,72011645.0,1079128.0,31003.0,The official video for Gorillaz - Rhinestone E...,True,True,3.100837e+08

For successful action
<div class='alert alert-block alert-success'>
    <b>Success</b>: This box indicates a successful action.

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20718 entries, 0 to 20717
Data columns (total 28 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        20718 non-null  int64
 1   Artist            20718 non-null  object
 2   Url_spotify       20718 non-null  object
 3   Track             20718 non-null  object
 4   Album             20718 non-null  object
 5   Album_type        20718 non-null  object
 6   Uri               20718 non-null  object
 7   Danceability      20716 non-null  float64
 8   Energy            20716 non-null  float64
 9   Key               20716 non-null  float64
 10  Loudness          20716 non-null  float64
 11  Speechiness       20716 non-null  float64
 12  Acousticness      20716 non-null  float64
 13  Instrumentalness  20716 non-null  float64
 14  Liveness          20716 non-null  float64
 15  Valence           20716 non-null  float64
 16  Tempo             20716 non-null  float64
 17  Duration_ms       20716 non-null  float64
 18  Url_youtube       20248 non-null  object
 19  Title             20248 non-null  object
 20  Channel           20248 non-null  object
 21  Views             20248 non-null  float64
 22  Likes             20177 non-null  float64
 23  Comments          20149 non-null  float64
 24  Description       19842 non-null  object
 25  Licensed          20248 non-null  object
 26  official_video    20248 non-null  object
 27  Stream            20142 non-null  float64
dtypes: float64(15), int64(1), object(12)
memory usage: 4.4+ MB

In [5]:
df

,Unnamed: 0,Artist,Url_spotify,Track,Album,Album_type,Uri,Danceability,Energy,Key,...,Url_youtube,Title,Channel,Views,Likes,Comments,Description,Licensed,official_video,Stream
0,0,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Feel Good Inc.,Demon Days,album,spotify:track:0d28khcov6AiegSCpG5TuT,0.818,0.705,6.0,...,https://www.youtube.com/watch?v=HyHNuVaZJ-k,Gorillaz - Feel Good Inc. (Official Video),Gorillaz,693555221.0,6220896.0,169907.0,Official HD Video for Gorillaz' fantastic trac...,True,True,1.040235e+09
1,1,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Rhinestone Eyes,Plastic Beach,album,spotify:track:1foMv2HQwfQ2vntFf9HFeG,0.676,0.703,8.0,...,https://www.youtube.com/watch?v=yYDmaexVHic,Gorillaz - Rhinestone Eyes [Storyboard Film] (...,Gorillaz,72011645.0,1079128.0,31003.0,The official video for Gorillaz - Rhinestone E...,True,True,3.100837e+08
2,2,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,New Gold (feat. Tame Impala and Bootie Brown),New Gold (feat. Tame Impala and Bootie Brown),single,spotify:track:64dLd6rVqDLtkXFYrEUHIU,0.695,0.923,1.0,...,https://www.youtube.com/watch?v=qJa-VFwPpYA,Gorillaz - New Gold ft. Tame Impala & Bootie B...,Gorillaz,8435055.0,282142.0,7399.0,Gorillaz - New Gold ft. Tame Impala & Bootie B...,True,True,6.306347e+07
3,3,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,On Melancholy Hill,Plastic Beach,album,spotify:track:0q6LuUqGLUiCPP1cbdwFs3,0.689,0.739,2.0,...,https://www.youtube.com/watch?v=04mfKJWDSzI,Gorillaz - On Melancholy Hill (Official Video),Gorillaz,211754952.0,1788577.0,55229.0,Follow Gorillaz online:\nhttp://gorillaz.com \...,True,True,4.346636e+08
4,4,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Clint Eastwood,Gorillaz,album,spotify:track:7yMiX7n9SBvadzox8T5jzT,0.663,0.694,10.0,...,https://www.youtube.com/watch?v=1V_xRb0x9aw,Gorillaz - Clint Eastwood (Official Video),Gorillaz,618480958.0,6197318.0,155930.0,The official music video for Gorillaz - Clint ...,True,True,6.172597e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20713,20713,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,JUST DANCE HARDSTYLE,JUST DANCE HARDSTYLE,single,spotify:track:0RtcKQGyI4hr8FgFH1TuYG,0.582,0.926,5.0,...,https://www.youtube.com/watch?v=5SHmKFKlNqI,JUST DANCE HARDSTYLE,SICK LEGEND - Topic,71678.0,1113.0,0.0,Provided to YouTube by Routenote\n\nJUST DANCE...,True,True,9.227144e+06
20714,20714,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,SET FIRE TO THE RAIN HARDSTYLE,SET FIRE TO THE RAIN HARDSTYLE,single,spotify:track:3rHvPA8lUnPBkaLyPOc0VV,0.531,0.936,4.0,...,https://www.youtube.com/watch?v=ocTH6KxllDQ,SET FIRE TO THE RAIN HARDSTYLE,SICK LEGEND - Topic,164741.0,2019.0,0.0,Provided to YouTube by Routenote\n\nSET FIRE T...,True,True,1.089818e+07
20715,20715,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,OUTSIDE HARDSTYLE SPED UP,OUTSIDE HARDSTYLE SPED UP,single,spotify:track:4jk00YxPtPbhvHJE9N4ddv,0.443,0.830,4.0,...,https://www.youtube.com/watch?v=5wFhE-HY0hg,OUTSIDE HARDSTYLE SPED UP,SICK LEGEND - Topic,35646.0,329.0,0.0,Provided to YouTube by Routenote\n\nOUTSIDE HA...,True,True,6.226110e+06
20716,20716,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,ONLY GIRL HARDSTYLE,ONLY GIRL HARDSTYLE,single,spotify:track:5EyErbpsugWliX006eTDex,0.417,0.767,9.0,...,https://www.youtube.com/watch?v=VMFLbFRNCn0,ONLY GIRL HARDSTYLE,SICK LEGEND - Topic,6533.0,88.0,0.0,Provided to YouTube by Routenote\n\nONLY GIRL ...,True,True,6.873961e+06
20717,20717,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,MISS YOU HARDSTYLE,MISS YOU HARDSTYLE,single,spotify:track:6lOn0jz1QpjcWeXo1oMm0k,0.498,0.938,6.0,...,https://www.youtube.com/watch?v=zau0dckCFi0,MISS YOU HARDSTYLE,SICK LEGEND - Topic,158697.0,2484.0,0.0,Provided to YouTube by Routenote\n\nMISS YOU H...,True,True,5.695584e+06

In [41]:
df.drop(columns=['Unnamed: 0'], inplace=True)

In [42]:
df

,Artist,Url_spotify,Track,Album,Album_type,Uri,Danceability,Energy,Key,Loudness,...,Url_youtube,Title,Channel,Views,Likes,Comments,Description,Licensed,official_video,Stream
0,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Feel Good Inc.,Demon Days,album,spotify:track:0d28khcov6AiegSCpG5TuT,0.818,0.705,6.0,-6.679,...,https://www.youtube.com/watch?v=HyHNuVaZJ-k,Gorillaz - Feel Good Inc. (Official Video),Gorillaz,693555221.0,6220896.0,169907.0,Official HD Video for Gorillaz' fantastic trac...,True,True,1.040235e+09
1,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Rhinestone Eyes,Plastic Beach,album,spotify:track:1foMv2HQwfQ2vntFf9HFeG,0.676,0.703,8.0,-5.815,...,https://www.youtube.com/watch?v=yYDmaexVHic,Gorillaz - Rhinestone Eyes [Storyboard Film] (...,Gorillaz,72011645.0,1079128.0,31003.0,The official video for Gorillaz - Rhinestone E...,True,True,3.100837e+08
2,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,New Gold (feat. Tame Impala and Bootie Brown),New Gold (feat. Tame Impala and Bootie Brown),single,spotify:track:64dLd6rVqDLtkXFYrEUHIU,0.695,0.923,1.0,-3.930,...,https://www.youtube.com/watch?v=qJa-VFwPpYA,Gorillaz - New Gold ft. Tame Impala & Bootie B...,Gorillaz,8435055.0,282142.0,7399.0,Gorillaz - New Gold ft. Tame Impala & Bootie B...,True,True,6.306347e+07
3,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,On Melancholy Hill,Plastic Beach,album,spotify:track:0q6LuUqGLUiCPP1cbdwFs3,0.689,0.739,2.0,-5.810,...,https://www.youtube.com/watch?v=04mfKJWDSzI,Gorillaz - On Melancholy Hill (Official Video),Gorillaz,211754952.0,1788577.0,55229.0,Follow Gorillaz online:\nhttp://gorillaz.com \...,True,True,4.346636e+08
4,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Clint Eastwood,Gorillaz,album,spotify:track:7yMiX7n9SBvadzox8T5jzT,0.663,0.694,10.0,-8.627,...,https://www.youtube.com/watch?v=1V_xRb0x9aw,Gorillaz - Clint Eastwood (Official Video),Gorillaz,618480958.0,6197318.0,155930.0,The official music video for Gorillaz - Clint ...,True,True,6.172597e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20713,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,JUST DANCE HARDSTYLE,JUST DANCE HARDSTYLE,single,spotify:track:0RtcKQGyI4hr8FgFH1TuYG,0.582,0.926,5.0,-6.344,...,https://www.youtube.com/watch?v=5SHmKFKlNqI,JUST DANCE HARDSTYLE,SICK LEGEND - Topic,71678.0,1113.0,0.0,Provided to YouTube by Routenote\n\nJUST DANCE...,True,True,9.227144e+06
20714,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,SET FIRE TO THE RAIN HARDSTYLE,SET FIRE TO THE RAIN HARDSTYLE,single,spotify:track:3rHvPA8lUnPBkaLyPOc0VV,0.531,0.936,4.0,-1.786,...,https://www.youtube.com/watch?v=ocTH6KxllDQ,SET FIRE TO THE RAIN HARDSTYLE,SICK LEGEND - Topic,164741.0,2019.0,0.0,Provided to YouTube by Routenote\n\nSET FIRE T...,True,True,1.089818e+07
20715,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,OUTSIDE HARDSTYLE SPED UP,OUTSIDE HARDSTYLE SPED UP,single,spotify:track:4jk00YxPtPbhvHJE9N4ddv,0.443,0.830,4.0,-4.679,...,https://www.youtube.com/watch?v=5wFhE-HY0hg,OUTSIDE HARDSTYLE SPED UP,SICK LEGEND - Topic,35646.0,329.0,0.0,Provided to YouTube by Routenote\n\nOUTSIDE HA...,True,True,6.226110e+06
20716,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,ONLY GIRL HARDSTYLE,ONLY GIRL HARDSTYLE,single,spotify:track:5EyErbpsugWliX006eTDex,0.417,0.767,9.0,-4.004,...,https://www.youtube.com/watch?v=VMFLbFRNCn0,ONLY GIRL HARDSTYLE,SICK LEGEND - Topic,6533.0,88.0,0.0,Provided to YouTube by Routenote\n\nONLY GIRL ...,True,True,6.873961e+06
20717,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,MISS YOU HARDSTYLE,MISS YOU HARDSTYLE,single,spotify:track:6lOn0jz1QpjcWeXo1oMm0k,0.498,0.938,6.0,-4.543,...,https://www.youtube.com/watch?v=zau0dckCFi0,MISS YOU HARDSTYLE,SICK LEGEND - Topic,158697.0,2484.0,0.0,Provided to YouTube by Routenote\n\nMISS YOU H...,True,True,5.695584e+06

In [28]:
df.columns

Index(['Artist', 'Url_spotify', 'Track', 'Album', 'Album_type', 'Uri',
       'Danceability', 'Energy', 'Key', 'Loudness', 'Speechiness',
       'Acousticness', 'Instrumentalness', 'Liveness', 'Valence', 'Tempo',
       'Duration_ms', 'Url_youtube', 'Title', 'Channel', 'Views', 'Likes',
       'Comments', 'Description', 'Licensed', 'official_video', 'Stream'],
      dtype='str')

In [50]:
type(df['Danceability'][0])

numpy.float64

In [58]:
df['Danceability'] =df['Danceability']* 100

In [52]:
df['Danceability']

0        81.8
1        67.6
2        69.5
3        68.9
4        66.3
         ...
20713    58.2
20714    53.1
20715    44.3
20716    41.7
20717    49.8
Name: Danceability, Length: 20718, dtype: float64

In [55]:
df['Energy']=df['Energy'] * 100

In [56]:
df['Energy']

0        70.5
1        70.3
2        92.3
3        73.9
4        69.4
         ...
20713    92.6
20714    93.6
20715    83.0
20716    76.7
20717    93.8
Name: Energy, Length: 20718, dtype: float64

In [75]:
df.isnull().sum()

Artist                0
Url_spotify           0
Track                 0
Album                 0
Album_type            0
Uri                   0
Danceability          2
Energy                2
Key                   2
Loudness              2
Speechiness           2
Acousticness          2
Instrumentalness      2
Liveness              2
Valence               2
Tempo                 2
Duration_ms           2
Url_youtube         470
Title               470
Channel             470
Views               470
Likes               541
Comments            569
Description         876
Licensed            470
official_video        0
Stream              576
dtype: int64

In [85]:
df.dropna(subset=['Danceability','Energy','Key','Loudness','Speechiness','Acousticness','Instrumentalness','Liveness','Valence','Tempo','Duration_ms'], inplace=True)

In [89]:
df.isnull().sum()

Artist                0
Url_spotify           0
Track                 0
Album                 0
Album_type            0
Uri                   0
Danceability          0
Energy                0
Key                   0
Loudness              0
Speechiness           0
Acousticness          0
Instrumentalness      0
Liveness              0
Valence               0
Tempo                 0
Duration_ms           0
Url_youtube         469
Title               469
Channel             469
Views               469
Likes               540
Comments            568
Description         875
Licensed            469
official_video        0
Stream              576
dtype: int64

In [90]:
df.duplicated().sum()

np.int64(0)

In [103]:
df['official_video'].info()

<class 'pandas.Series'>
Index: 20716 entries, 0 to 20717
Series name: official_video
Non-Null Count  Dtype
--------------  -----
20716 non-null  bool
dtypes: bool(1)
memory usage: 182.1 KB

In [104]:
df['Licensed'].info()

<class 'pandas.Series'>
Index: 20716 entries, 0 to 20717
Series name: Licensed
Non-Null Count  Dtype
--------------  -----
20247 non-null  object
dtypes: object(1)
memory usage: 323.7+ KB

In [105]:
df['Licensed'] = df['Licensed'].astype('bool')

In [106]:
df['Licensed'].info()

<class 'pandas.Series'>
Index: 20716 entries, 0 to 20717
Series name: Licensed
Non-Null Count  Dtype
--------------  -----
20716 non-null  bool
dtypes: bool(1)
memory usage: 182.1 KB

In [108]:
df['Stream'].info()

<class 'pandas.Series'>
Index: 20716 entries, 0 to 20717
Series name: Stream
Non-Null Count  Dtype
--------------  -----
20140 non-null  float64
dtypes: float64(1)
memory usage: 323.7 KB

In [111]:
df['Description'] = df['Description'].str.replace('\n',' ')

In [123]:
df['Description']

0        Official HD Video for Gorillaz' fantastic trac...
1        The official video for Gorillaz - Rhinestone E...
2        Gorillaz - New Gold ft. Tame Impala & Bootie B...
3        Follow Gorillaz online: http://gorillaz.com  h...
4        The official music video for Gorillaz - Clint ...
                               ...
20713    Provided to YouTube by Routenote  JUST DANCE H...
20714    Provided to YouTube by Routenote  SET FIRE TO ...
20715    Provided to YouTube by Routenote  OUTSIDE HARD...
20716    Provided to YouTube by Routenote  ONLY GIRL HA...
20717    Provided to YouTube by Routenote  MISS YOU HAR...
Name: Description, Length: 20716, dtype: str

In [120]:
df['Title']=df['Title'].str.capitalize()

In [122]:
df['Title']

0               Gorillaz - feel good inc. (official video)
1        Gorillaz - rhinestone eyes [storyboard film] (...
2        Gorillaz - new gold ft. tame impala & bootie b...
3           Gorillaz - on melancholy hill (official video)
4               Gorillaz - clint eastwood (official video)
                               ...
20713                                 Just dance hardstyle
20714                       Set fire to the rain hardstyle
20715                            Outside hardstyle sped up
20716                                  Only girl hardstyle
20717                                   Miss you hardstyle
Name: Title, Length: 20716, dtype: str

In [125]:
df['Artist']=df['Artist'].str.capitalize()

In [127]:
df['Track']=df['Track'].str.capitalize()

In [128]:
df['Album']=df['Album'].str.capitalize()

In [130]:
df['Channel']=df['Channel'].str.capitalize()

In [136]:
df.rename(columns={'Uri':'URI_spotify', 'Url_youtube':'URL_youtube','Url_spotify':'URL_spotify', 'Stream':'Streams'}, inplace=True)

In [137]:
df.columns

Index(['Artist', 'URL_spotify', 'Track', 'Album', 'Album_type', 'URI_spotify',
       'Danceability', 'Energy', 'Key', 'Loudness', 'Speechiness',
       'Acousticness', 'Instrumentalness', 'Liveness', 'Valence', 'Tempo',
       'Duration_ms', 'URL_youtube', 'Title', 'Channel', 'Views', 'Likes',
       'Comments', 'Description', 'Licensed', 'official_video', 'Streams'],
      dtype='str')

In [138]:
df

,Artist,URL_spotify,Track,Album,Album_type,URI_spotify,Danceability,Energy,Key,Loudness,...,URL_youtube,Title,Channel,Views,Likes,Comments,Description,Licensed,official_video,Streams
0,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Feel good inc.,Demon days,album,spotify:track:0d28khcov6AiegSCpG5TuT,8180.0,70.5,6.0,-6.679,...,https://www.youtube.com/watch?v=HyHNuVaZJ-k,Gorillaz - feel good inc. (official video),Gorillaz,693555221.0,6220896.0,169907.0,Official HD Video for Gorillaz' fantastic trac...,True,True,1.040235e+09
1,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Rhinestone eyes,Plastic beach,album,spotify:track:1foMv2HQwfQ2vntFf9HFeG,6760.0,70.3,8.0,-5.815,...,https://www.youtube.com/watch?v=yYDmaexVHic,Gorillaz - rhinestone eyes [storyboard film] (...,Gorillaz,72011645.0,1079128.0,31003.0,The official video for Gorillaz - Rhinestone E...,True,True,3.100837e+08
2,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,New gold (feat. tame impala and bootie brown),New gold (feat. tame impala and bootie brown),single,spotify:track:64dLd6rVqDLtkXFYrEUHIU,6950.0,92.3,1.0,-3.930,...,https://www.youtube.com/watch?v=qJa-VFwPpYA,Gorillaz - new gold ft. tame impala & bootie b...,Gorillaz,8435055.0,282142.0,7399.0,Gorillaz - New Gold ft. Tame Impala & Bootie B...,True,True,6.306347e+07
3,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,On melancholy hill,Plastic beach,album,spotify:track:0q6LuUqGLUiCPP1cbdwFs3,6890.0,73.9,2.0,-5.810,...,https://www.youtube.com/watch?v=04mfKJWDSzI,Gorillaz - on melancholy hill (official video),Gorillaz,211754952.0,1788577.0,55229.0,Follow Gorillaz online: http://gorillaz.com h...,True,True,4.346636e+08
4,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Clint eastwood,Gorillaz,album,spotify:track:7yMiX7n9SBvadzox8T5jzT,6630.0,69.4,10.0,-8.627,...,https://www.youtube.com/watch?v=1V_xRb0x9aw,Gorillaz - clint eastwood (official video),Gorillaz,618480958.0,6197318.0,155930.0,The official music video for Gorillaz - Clint ...,True,True,6.172597e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20713,Sick legend,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,Just dance hardstyle,Just dance hardstyle,single,spotify:track:0RtcKQGyI4hr8FgFH1TuYG,5820.0,92.6,5.0,-6.344,...,https://www.youtube.com/watch?v=5SHmKFKlNqI,Just dance hardstyle,Sick legend - topic,71678.0,1113.0,0.0,Provided to YouTube by Routenote JUST DANCE H...,True,True,9.227144e+06
20714,Sick legend,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,Set fire to the rain hardstyle,Set fire to the rain hardstyle,single,spotify:track:3rHvPA8lUnPBkaLyPOc0VV,5310.0,93.6,4.0,-1.786,...,https://www.youtube.com/watch?v=ocTH6KxllDQ,Set fire to the rain hardstyle,Sick legend - topic,164741.0,2019.0,0.0,Provided to YouTube by Routenote SET FIRE TO ...,True,True,1.089818e+07
20715,Sick legend,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,Outside hardstyle sped up,Outside hardstyle sped up,single,spotify:track:4jk00YxPtPbhvHJE9N4ddv,4430.0,83.0,4.0,-4.679,...,https://www.youtube.com/watch?v=5wFhE-HY0hg,Outside hardstyle sped up,Sick legend - topic,35646.0,329.0,0.0,Provided to YouTube by Routenote OUTSIDE HARD...,True,True,6.226110e+06
20716,Sick legend,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,Only girl hardstyle,Only girl hardstyle,single,spotify:track:5EyErbpsugWliX006eTDex,4170.0,76.7,9.0,-4.004,...,https://www.youtube.com/watch?v=VMFLbFRNCn0,Only girl hardstyle,Sick legend - topic,6533.0,88.0,0.0,Provided to YouTube by Routenote ONLY GIRL HA...,True,True,6.873961e+06
20717,Sick legend,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,Miss you hardstyle,Miss you hardstyle,single,spotify:track:6lOn0jz1QpjcWeXo1oMm0k,4980.0,93.8,6.0,-4.543,...,https://www.youtube.com/watch?v=zau0dckCFi0,Miss you hardstyle,Sick legend - topic,158697.0,2484.0,0.0,Provided to YouTube by Routenote MISS YOU HAR...,True,True,5.695584e+06