In [194]:
import pandas as pd
import numpy as np

## **Read Data**

In [195]:
df = pd.read_csv('../Data/Spotify_Youtube.csv')

In [196]:
df.head(3)

,Unnamed: 0,Artist,Url_spotify,Track,Album,Album_type,Uri,Danceability,Energy,Key,...,Url_youtube,Title,Channel,Views,Likes,Comments,Description,Licensed,official_video,Stream
0,0,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Feel Good Inc.,Demon Days,album,spotify:track:0d28khcov6AiegSCpG5TuT,0.818,0.705,6.0,...,https://www.youtube.com/watch?v=HyHNuVaZJ-k,Gorillaz - Feel Good Inc. (Official Video),Gorillaz,693555221.0,6220896.0,169907.0,Official HD Video for Gorillaz' fantastic trac...,True,True,1.040235e+09
1,1,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Rhinestone Eyes,Plastic Beach,album,spotify:track:1foMv2HQwfQ2vntFf9HFeG,0.676,0.703,8.0,...,https://www.youtube.com/watch?v=yYDmaexVHic,Gorillaz - Rhinestone Eyes [Storyboard Film] (...,Gorillaz,72011645.0,1079128.0,31003.0,The official video for Gorillaz - Rhinestone E...,True,True,3.100837e+08
2,2,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,New Gold (feat. Tame Impala and Bootie Brown),New Gold (feat. Tame Impala and Bootie Brown),single,spotify:track:64dLd6rVqDLtkXFYrEUHIU,0.695,0.923,1.0,...,https://www.youtube.com/watch?v=qJa-VFwPpYA,Gorillaz - New Gold ft. Tame Impala & Bootie B...,Gorillaz,8435055.0,282142.0,7399.0,Gorillaz - New Gold ft. Tame Impala & Bootie B...,True,True,6.306347e+07

For successful action
<div class='alert alert-block alert-success'>
    <b>Success</b>: This box indicates a successful action.

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## **Data Cleaning**

In [197]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20718 entries, 0 to 20717
Data columns (total 28 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        20718 non-null  int64
 1   Artist            20718 non-null  str
 2   Url_spotify       20718 non-null  str
 3   Track             20718 non-null  str
 4   Album             20718 non-null  str
 5   Album_type        20718 non-null  str
 6   Uri               20718 non-null  str
 7   Danceability      20716 non-null  float64
 8   Energy            20716 non-null  float64
 9   Key               20716 non-null  float64
 10  Loudness          20716 non-null  float64
 11  Speechiness       20716 non-null  float64
 12  Acousticness      20716 non-null  float64
 13  Instrumentalness  20716 non-null  float64
 14  Liveness          20716 non-null  float64
 15  Valence           20716 non-null  float64
 16  Tempo             20716 non-null  float64
 17  Duration_ms       20716 non-null  float64
 18  Url_youtube       20248 non-null  str
 19  Title             20248 non-null  str
 20  Channel           20248 non-null  str
 21  Views             20248 non-null  float64
 22  Likes             20177 non-null  float64
 23  Comments          20149 non-null  float64
 24  Description       19842 non-null  str
 25  Licensed          20248 non-null  object
 26  official_video    20248 non-null  object
 27  Stream            20142 non-null  float64
dtypes: float64(15), int64(1), object(2), str(10)
memory usage: 4.4+ MB

In [198]:
df

,Unnamed: 0,Artist,Url_spotify,Track,Album,Album_type,Uri,Danceability,Energy,Key,...,Url_youtube,Title,Channel,Views,Likes,Comments,Description,Licensed,official_video,Stream
0,0,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Feel Good Inc.,Demon Days,album,spotify:track:0d28khcov6AiegSCpG5TuT,0.818,0.705,6.0,...,https://www.youtube.com/watch?v=HyHNuVaZJ-k,Gorillaz - Feel Good Inc. (Official Video),Gorillaz,693555221.0,6220896.0,169907.0,Official HD Video for Gorillaz' fantastic trac...,True,True,1.040235e+09
1,1,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Rhinestone Eyes,Plastic Beach,album,spotify:track:1foMv2HQwfQ2vntFf9HFeG,0.676,0.703,8.0,...,https://www.youtube.com/watch?v=yYDmaexVHic,Gorillaz - Rhinestone Eyes [Storyboard Film] (...,Gorillaz,72011645.0,1079128.0,31003.0,The official video for Gorillaz - Rhinestone E...,True,True,3.100837e+08
2,2,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,New Gold (feat. Tame Impala and Bootie Brown),New Gold (feat. Tame Impala and Bootie Brown),single,spotify:track:64dLd6rVqDLtkXFYrEUHIU,0.695,0.923,1.0,...,https://www.youtube.com/watch?v=qJa-VFwPpYA,Gorillaz - New Gold ft. Tame Impala & Bootie B...,Gorillaz,8435055.0,282142.0,7399.0,Gorillaz - New Gold ft. Tame Impala & Bootie B...,True,True,6.306347e+07
3,3,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,On Melancholy Hill,Plastic Beach,album,spotify:track:0q6LuUqGLUiCPP1cbdwFs3,0.689,0.739,2.0,...,https://www.youtube.com/watch?v=04mfKJWDSzI,Gorillaz - On Melancholy Hill (Official Video),Gorillaz,211754952.0,1788577.0,55229.0,Follow Gorillaz online:\nhttp://gorillaz.com \...,True,True,4.346636e+08
4,4,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Clint Eastwood,Gorillaz,album,spotify:track:7yMiX7n9SBvadzox8T5jzT,0.663,0.694,10.0,...,https://www.youtube.com/watch?v=1V_xRb0x9aw,Gorillaz - Clint Eastwood (Official Video),Gorillaz,618480958.0,6197318.0,155930.0,The official music video for Gorillaz - Clint ...,True,True,6.172597e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20713,20713,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,JUST DANCE HARDSTYLE,JUST DANCE HARDSTYLE,single,spotify:track:0RtcKQGyI4hr8FgFH1TuYG,0.582,0.926,5.0,...,https://www.youtube.com/watch?v=5SHmKFKlNqI,JUST DANCE HARDSTYLE,SICK LEGEND - Topic,71678.0,1113.0,0.0,Provided to YouTube by Routenote\n\nJUST DANCE...,True,True,9.227144e+06
20714,20714,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,SET FIRE TO THE RAIN HARDSTYLE,SET FIRE TO THE RAIN HARDSTYLE,single,spotify:track:3rHvPA8lUnPBkaLyPOc0VV,0.531,0.936,4.0,...,https://www.youtube.com/watch?v=ocTH6KxllDQ,SET FIRE TO THE RAIN HARDSTYLE,SICK LEGEND - Topic,164741.0,2019.0,0.0,Provided to YouTube by Routenote\n\nSET FIRE T...,True,True,1.089818e+07
20715,20715,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,OUTSIDE HARDSTYLE SPED UP,OUTSIDE HARDSTYLE SPED UP,single,spotify:track:4jk00YxPtPbhvHJE9N4ddv,0.443,0.830,4.0,...,https://www.youtube.com/watch?v=5wFhE-HY0hg,OUTSIDE HARDSTYLE SPED UP,SICK LEGEND - Topic,35646.0,329.0,0.0,Provided to YouTube by Routenote\n\nOUTSIDE HA...,True,True,6.226110e+06
20716,20716,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,ONLY GIRL HARDSTYLE,ONLY GIRL HARDSTYLE,single,spotify:track:5EyErbpsugWliX006eTDex,0.417,0.767,9.0,...,https://www.youtube.com/watch?v=VMFLbFRNCn0,ONLY GIRL HARDSTYLE,SICK LEGEND - Topic,6533.0,88.0,0.0,Provided to YouTube by Routenote\n\nONLY GIRL ...,True,True,6.873961e+06
20717,20717,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,MISS YOU HARDSTYLE,MISS YOU HARDSTYLE,single,spotify:track:6lOn0jz1QpjcWeXo1oMm0k,0.498,0.938,6.0,...,https://www.youtube.com/watch?v=zau0dckCFi0,MISS YOU HARDSTYLE,SICK LEGEND - Topic,158697.0,2484.0,0.0,Provided to YouTube by Routenote\n\nMISS YOU H...,True,True,5.695584e+06

### **Drop Unnamed Index Column**

In [199]:
df.drop(columns=['Unnamed: 0'], inplace=True)

In [200]:
df.head(2)

,Artist,Url_spotify,Track,Album,Album_type,Uri,Danceability,Energy,Key,Loudness,...,Url_youtube,Title,Channel,Views,Likes,Comments,Description,Licensed,official_video,Stream
0,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Feel Good Inc.,Demon Days,album,spotify:track:0d28khcov6AiegSCpG5TuT,0.818,0.705,6.0,-6.679,...,https://www.youtube.com/watch?v=HyHNuVaZJ-k,Gorillaz - Feel Good Inc. (Official Video),Gorillaz,693555221.0,6220896.0,169907.0,Official HD Video for Gorillaz' fantastic trac...,True,True,1.040235e+09
1,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Rhinestone Eyes,Plastic Beach,album,spotify:track:1foMv2HQwfQ2vntFf9HFeG,0.676,0.703,8.0,-5.815,...,https://www.youtube.com/watch?v=yYDmaexVHic,Gorillaz - Rhinestone Eyes [Storyboard Film] (...,Gorillaz,72011645.0,1079128.0,31003.0,The official video for Gorillaz - Rhinestone E...,True,True,3.100837e+08

### **Converting Danceability and Energy into Percentage**

In [201]:
df['Danceability'] =df['Danceability']* 100

In [202]:
df['Danceability']

0        81.8
1        67.6
2        69.5
3        68.9
4        66.3
         ...
20713    58.2
20714    53.1
20715    44.3
20716    41.7
20717    49.8
Name: Danceability, Length: 20718, dtype: float64

In [203]:
df['Energy']=df['Energy'] * 100

In [204]:
df['Energy']

0        70.5
1        70.3
2        92.3
3        73.9
4        69.4
         ...
20713    92.6
20714    93.6
20715    83.0
20716    76.7
20717    93.8
Name: Energy, Length: 20718, dtype: float64

### **Handle Missing Values**

In [205]:
df.isnull().sum()

Artist                0
Url_spotify           0
Track                 0
Album                 0
Album_type            0
Uri                   0
Danceability          2
Energy                2
Key                   2
Loudness              2
Speechiness           2
Acousticness          2
Instrumentalness      2
Liveness              2
Valence               2
Tempo                 2
Duration_ms           2
Url_youtube         470
Title               470
Channel             470
Views               470
Likes               541
Comments            569
Description         876
Licensed            470
official_video      470
Stream              576
dtype: int64

In [206]:
df.dropna(subset=['Danceability','Energy','Key','Loudness','Speechiness','Acousticness','Instrumentalness','Liveness','Valence','Tempo','Duration_ms'], inplace=True)

In [207]:
df.isnull().sum()

Artist                0
Url_spotify           0
Track                 0
Album                 0
Album_type            0
Uri                   0
Danceability          0
Energy                0
Key                   0
Loudness              0
Speechiness           0
Acousticness          0
Instrumentalness      0
Liveness              0
Valence               0
Tempo                 0
Duration_ms           0
Url_youtube         469
Title               469
Channel             469
Views               469
Likes               540
Comments            568
Description         875
Licensed            469
official_video      469
Stream              576
dtype: int64

### **Check Duplicates**

In [208]:
df.duplicated().sum()

np.int64(0)

### **Fix Data Types**

In [209]:
df['official_video'].info()

<class 'pandas.Series'>
Index: 20716 entries, 0 to 20717
Series name: official_video
Non-Null Count  Dtype
--------------  -----
20247 non-null  object
dtypes: object(1)
memory usage: 323.7+ KB

In [210]:
df['official_video'] = df['official_video'].astype('bool')

In [211]:
df['official_video'].info()

<class 'pandas.Series'>
Index: 20716 entries, 0 to 20717
Series name: official_video
Non-Null Count  Dtype
--------------  -----
20716 non-null  bool
dtypes: bool(1)
memory usage: 182.1 KB

In [212]:
df['Licensed'].info()

<class 'pandas.Series'>
Index: 20716 entries, 0 to 20717
Series name: Licensed
Non-Null Count  Dtype
--------------  -----
20247 non-null  object
dtypes: object(1)
memory usage: 323.7+ KB

In [213]:
df['Licensed'] = df['Licensed'].astype('bool')

In [214]:
df['Licensed'].info()

<class 'pandas.Series'>
Index: 20716 entries, 0 to 20717
Series name: Licensed
Non-Null Count  Dtype
--------------  -----
20716 non-null  bool
dtypes: bool(1)
memory usage: 182.1 KB

### **Clean Description Column**

In [215]:
df['Description'] = df['Description'].str.replace('\n',' ')

In [216]:
df['Description']

0        Official HD Video for Gorillaz' fantastic trac...
1        The official video for Gorillaz - Rhinestone E...
2        Gorillaz - New Gold ft. Tame Impala & Bootie B...
3        Follow Gorillaz online: http://gorillaz.com  h...
4        The official music video for Gorillaz - Clint ...
                               ...
20713    Provided to YouTube by Routenote  JUST DANCE H...
20714    Provided to YouTube by Routenote  SET FIRE TO ...
20715    Provided to YouTube by Routenote  OUTSIDE HARD...
20716    Provided to YouTube by Routenote  ONLY GIRL HA...
20717    Provided to YouTube by Routenote  MISS YOU HAR...
Name: Description, Length: 20716, dtype: str

### **Text Capitalization**

In [217]:
df['Title']=df['Title'].str.capitalize()

In [218]:
df['Title']

0               Gorillaz - feel good inc. (official video)
1        Gorillaz - rhinestone eyes [storyboard film] (...
2        Gorillaz - new gold ft. tame impala & bootie b...
3           Gorillaz - on melancholy hill (official video)
4               Gorillaz - clint eastwood (official video)
                               ...
20713                                 Just dance hardstyle
20714                       Set fire to the rain hardstyle
20715                            Outside hardstyle sped up
20716                                  Only girl hardstyle
20717                                   Miss you hardstyle
Name: Title, Length: 20716, dtype: str

In [219]:
df['Artist']=df['Artist'].str.capitalize()

In [220]:
df['Artist']

0           Gorillaz
1           Gorillaz
2           Gorillaz
3           Gorillaz
4           Gorillaz
            ...
20713    Sick legend
20714    Sick legend
20715    Sick legend
20716    Sick legend
20717    Sick legend
Name: Artist, Length: 20716, dtype: str

In [221]:
df['Track']=df['Track'].str.capitalize()

In [222]:
df['Track']

0                                       Feel good inc.
1                                      Rhinestone eyes
2        New gold (feat. tame impala and bootie brown)
3                                   On melancholy hill
4                                       Clint eastwood
                             ...
20713                             Just dance hardstyle
20714                   Set fire to the rain hardstyle
20715                        Outside hardstyle sped up
20716                              Only girl hardstyle
20717                               Miss you hardstyle
Name: Track, Length: 20716, dtype: str

In [223]:
df['Album']=df['Album'].str.capitalize()

In [224]:
df['Album']

0                                           Demon days
1                                        Plastic beach
2        New gold (feat. tame impala and bootie brown)
3                                        Plastic beach
4                                             Gorillaz
                             ...
20713                             Just dance hardstyle
20714                   Set fire to the rain hardstyle
20715                        Outside hardstyle sped up
20716                              Only girl hardstyle
20717                               Miss you hardstyle
Name: Album, Length: 20716, dtype: str

In [225]:
df['Channel']=df['Channel'].str.capitalize()

In [226]:
df['Channel']

0                   Gorillaz
1                   Gorillaz
2                   Gorillaz
3                   Gorillaz
4                   Gorillaz
                ...
20713    Sick legend - topic
20714    Sick legend - topic
20715    Sick legend - topic
20716    Sick legend - topic
20717    Sick legend - topic
Name: Channel, Length: 20716, dtype: str

### **Rename Columns**

In [227]:
df.columns

Index(['Artist', 'Url_spotify', 'Track', 'Album', 'Album_type', 'Uri',
       'Danceability', 'Energy', 'Key', 'Loudness', 'Speechiness',
       'Acousticness', 'Instrumentalness', 'Liveness', 'Valence', 'Tempo',
       'Duration_ms', 'Url_youtube', 'Title', 'Channel', 'Views', 'Likes',
       'Comments', 'Description', 'Licensed', 'official_video', 'Stream'],
      dtype='str')

In [228]:
df.rename(columns={'Uri':'URI_spotify', 'Url_youtube':'URL_youtube','Url_spotify':'URL_spotify', 'Stream':'Streams'}, inplace=True)

In [229]:
df.columns

Index(['Artist', 'URL_spotify', 'Track', 'Album', 'Album_type', 'URI_spotify',
       'Danceability', 'Energy', 'Key', 'Loudness', 'Speechiness',
       'Acousticness', 'Instrumentalness', 'Liveness', 'Valence', 'Tempo',
       'Duration_ms', 'URL_youtube', 'Title', 'Channel', 'Views', 'Likes',
       'Comments', 'Description', 'Licensed', 'official_video', 'Streams'],
      dtype='str')

In [230]:
df

,Artist,URL_spotify,Track,Album,Album_type,URI_spotify,Danceability,Energy,Key,Loudness,...,URL_youtube,Title,Channel,Views,Likes,Comments,Description,Licensed,official_video,Streams
0,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Feel good inc.,Demon days,album,spotify:track:0d28khcov6AiegSCpG5TuT,81.8,70.5,6.0,-6.679,...,https://www.youtube.com/watch?v=HyHNuVaZJ-k,Gorillaz - feel good inc. (official video),Gorillaz,693555221.0,6220896.0,169907.0,Official HD Video for Gorillaz' fantastic trac...,True,True,1.040235e+09
1,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Rhinestone eyes,Plastic beach,album,spotify:track:1foMv2HQwfQ2vntFf9HFeG,67.6,70.3,8.0,-5.815,...,https://www.youtube.com/watch?v=yYDmaexVHic,Gorillaz - rhinestone eyes [storyboard film] (...,Gorillaz,72011645.0,1079128.0,31003.0,The official video for Gorillaz - Rhinestone E...,True,True,3.100837e+08
2,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,New gold (feat. tame impala and bootie brown),New gold (feat. tame impala and bootie brown),single,spotify:track:64dLd6rVqDLtkXFYrEUHIU,69.5,92.3,1.0,-3.930,...,https://www.youtube.com/watch?v=qJa-VFwPpYA,Gorillaz - new gold ft. tame impala & bootie b...,Gorillaz,8435055.0,282142.0,7399.0,Gorillaz - New Gold ft. Tame Impala & Bootie B...,True,True,6.306347e+07
3,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,On melancholy hill,Plastic beach,album,spotify:track:0q6LuUqGLUiCPP1cbdwFs3,68.9,73.9,2.0,-5.810,...,https://www.youtube.com/watch?v=04mfKJWDSzI,Gorillaz - on melancholy hill (official video),Gorillaz,211754952.0,1788577.0,55229.0,Follow Gorillaz online: http://gorillaz.com h...,True,True,4.346636e+08
4,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Clint eastwood,Gorillaz,album,spotify:track:7yMiX7n9SBvadzox8T5jzT,66.3,69.4,10.0,-8.627,...,https://www.youtube.com/watch?v=1V_xRb0x9aw,Gorillaz - clint eastwood (official video),Gorillaz,618480958.0,6197318.0,155930.0,The official music video for Gorillaz - Clint ...,True,True,6.172597e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20713,Sick legend,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,Just dance hardstyle,Just dance hardstyle,single,spotify:track:0RtcKQGyI4hr8FgFH1TuYG,58.2,92.6,5.0,-6.344,...,https://www.youtube.com/watch?v=5SHmKFKlNqI,Just dance hardstyle,Sick legend - topic,71678.0,1113.0,0.0,Provided to YouTube by Routenote JUST DANCE H...,True,True,9.227144e+06
20714,Sick legend,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,Set fire to the rain hardstyle,Set fire to the rain hardstyle,single,spotify:track:3rHvPA8lUnPBkaLyPOc0VV,53.1,93.6,4.0,-1.786,...,https://www.youtube.com/watch?v=ocTH6KxllDQ,Set fire to the rain hardstyle,Sick legend - topic,164741.0,2019.0,0.0,Provided to YouTube by Routenote SET FIRE TO ...,True,True,1.089818e+07
20715,Sick legend,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,Outside hardstyle sped up,Outside hardstyle sped up,single,spotify:track:4jk00YxPtPbhvHJE9N4ddv,44.3,83.0,4.0,-4.679,...,https://www.youtube.com/watch?v=5wFhE-HY0hg,Outside hardstyle sped up,Sick legend - topic,35646.0,329.0,0.0,Provided to YouTube by Routenote OUTSIDE HARD...,True,True,6.226110e+06
20716,Sick legend,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,Only girl hardstyle,Only girl hardstyle,single,spotify:track:5EyErbpsugWliX006eTDex,41.7,76.7,9.0,-4.004,...,https://www.youtube.com/watch?v=VMFLbFRNCn0,Only girl hardstyle,Sick legend - topic,6533.0,88.0,0.0,Provided to YouTube by Routenote ONLY GIRL HA...,True,True,6.873961e+06
20717,Sick legend,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,Miss you hardstyle,Miss you hardstyle,single,spotify:track:6lOn0jz1QpjcWeXo1oMm0k,49.8,93.8,6.0,-4.543,...,https://www.youtube.com/watch?v=zau0dckCFi0,Miss you hardstyle,Sick legend - topic,158697.0,2484.0,0.0,Provided to YouTube by Routenote MISS YOU HAR...,True,True,5.695584e+06

## **Data Analysis**

In [231]:
df.head()

,Artist,URL_spotify,Track,Album,Album_type,URI_spotify,Danceability,Energy,Key,Loudness,...,URL_youtube,Title,Channel,Views,Likes,Comments,Description,Licensed,official_video,Streams
0,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Feel good inc.,Demon days,album,spotify:track:0d28khcov6AiegSCpG5TuT,81.8,70.5,6.0,-6.679,...,https://www.youtube.com/watch?v=HyHNuVaZJ-k,Gorillaz - feel good inc. (official video),Gorillaz,693555221.0,6220896.0,169907.0,Official HD Video for Gorillaz' fantastic trac...,True,True,1.040235e+09
1,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Rhinestone eyes,Plastic beach,album,spotify:track:1foMv2HQwfQ2vntFf9HFeG,67.6,70.3,8.0,-5.815,...,https://www.youtube.com/watch?v=yYDmaexVHic,Gorillaz - rhinestone eyes [storyboard film] (...,Gorillaz,72011645.0,1079128.0,31003.0,The official video for Gorillaz - Rhinestone E...,True,True,3.100837e+08
2,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,New gold (feat. tame impala and bootie brown),New gold (feat. tame impala and bootie brown),single,spotify:track:64dLd6rVqDLtkXFYrEUHIU,69.5,92.3,1.0,-3.930,...,https://www.youtube.com/watch?v=qJa-VFwPpYA,Gorillaz - new gold ft. tame impala & bootie b...,Gorillaz,8435055.0,282142.0,7399.0,Gorillaz - New Gold ft. Tame Impala & Bootie B...,True,True,6.306347e+07
3,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,On melancholy hill,Plastic beach,album,spotify:track:0q6LuUqGLUiCPP1cbdwFs3,68.9,73.9,2.0,-5.810,...,https://www.youtube.com/watch?v=04mfKJWDSzI,Gorillaz - on melancholy hill (official video),Gorillaz,211754952.0,1788577.0,55229.0,Follow Gorillaz online: http://gorillaz.com h...,True,True,4.346636e+08
4,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Clint eastwood,Gorillaz,album,spotify:track:7yMiX7n9SBvadzox8T5jzT,66.3,69.4,10.0,-8.627,...,https://www.youtube.com/watch?v=1V_xRb0x9aw,Gorillaz - clint eastwood (official video),Gorillaz,618480958.0,6197318.0,155930.0,The official music video for Gorillaz - Clint ...,True,True,6.172597e+08

In [232]:
df.describe()

,Danceability,Energy,Key,Loudness,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Duration_ms,Views,Likes,Comments,Streams
count,20716.000000,20716.000000,20716.000000,20716.000000,20716.000000,20716.000000,20716.000000,20716.000000,20716.000000,20716.000000,2.071600e+04,2.024700e+04,2.017600e+04,2.014800e+04,2.014000e+04
mean,61.977745,63.525035,5.300348,-7.671680,0.096456,0.291535,0.055962,0.193521,0.529853,120.638340,2.247176e+05,9.394139e+07,6.633658e+05,2.751997e+04,1.359430e+08
std,16.527239,21.414683,3.576449,4.632749,0.111960,0.286299,0.193262,0.168531,0.245441,29.579018,1.247905e+05,2.746506e+08,1.789365e+06,1.932394e+05,2.441441e+08
min,0.000000,0.002030,0.000000,-46.251000,0.000000,0.000001,0.000000,0.014500,0.000000,0.000000,3.098500e+04,0.000000e+00,0.000000e+00,0.000000e+00,6.574000e+03
25%,51.800000,50.700000,2.000000,-8.858000,0.035700,0.045200,0.000000,0.094100,0.339000,97.002000,1.800095e+05,1.825713e+06,2.157500e+04,5.090000e+02,1.767260e+07
50%,63.700000,66.600000,5.000000,-6.536000,0.050500,0.193000,0.000002,0.125000,0.537000,119.965000,2.132845e+05,1.450110e+07,1.244745e+05,3.277000e+03,4.967698e+07
75%,74.025000,79.800000,8.000000,-4.931000,0.103000,0.477250,0.000463,0.237000,0.726250,139.935000,2.524430e+05,7.039975e+07,5.221765e+05,1.436000e+04,1.383525e+08
max,97.500000,100.000000,11.000000,0.920000,0.964000,0.996000,1.000000,1.000000,0.993000,243.372000,4.676058e+06,8.079649e+09,5.078865e+07,1.608314e+07,3.386520e+09

### **Video with Highest Views**

In [233]:
df['Views'].max()

np.float64(8079649362.0)

In [234]:
df[df['Views']==df['Views'].max()]

,Artist,URL_spotify,Track,Album,Album_type,URI_spotify,Danceability,Energy,Key,Loudness,...,URL_youtube,Title,Channel,Views,Likes,Comments,Description,Licensed,official_video,Streams
1147,Luis fonsi,https://open.spotify.com/artist/4V8Sr092TqfHkf...,Despacito,Vida,album,spotify:track:6habFhsOp2NvshLv26DqMb,65.5,79.7,2.0,-4.787,...,https://www.youtube.com/watch?v=kJQP7kiw5Fk,Luis fonsi - despacito ft. daddy yankee,Luisfonsivevo,8.079649e+09,50788652.0,4252791.0,“Despacito” disponible ya en todas las platafo...,True,True,1.506598e+09

In [235]:
cols=['Artist','Track','Album','Channel','Title','Views','Likes']

In [236]:
df[df['Views']==df['Views'].max()][cols]

,Artist,Track,Album,Channel,Title,Views,Likes
1147,Luis fonsi,Despacito,Vida,Luisfonsivevo,Luis fonsi - despacito ft. daddy yankee,8.079649e+09,50788652.0

### **Video with Lowest Views**

In [237]:
df['Views'].min()

np.float64(0.0)

In [238]:
df[df['Views']==df['Views'].min()]

,Artist,URL_spotify,Track,Album,Album_type,URI_spotify,Danceability,Energy,Key,Loudness,...,URL_youtube,Title,Channel,Views,Likes,Comments,Description,Licensed,official_video,Streams
5898,Santiago ziesmer,https://open.spotify.com/artist/5isi7xwETQC1Hb...,Kapitel 5.2 & kapitel 6.1 - die kleine hexe - ...,Die kleine hexe - das hörspiel,album,spotify:track:3SiBe9HRopGnuzfl4s2pWw,59.9,24.1,10.0,-17.925,...,https://www.youtube.com/watch?v=z04b-pMl864,Kapitel 5.2 - hundeherz,Various artists - topic,0.0,0.0,0.0,Provided to YouTube by Bookwire Kapitel 5.2 -...,True,True,NaN

In [239]:
df[df['Views']==df['Views'].min()][cols]

,Artist,Track,Album,Channel,Title,Views,Likes
5898,Santiago ziesmer,Kapitel 5.2 & kapitel 6.1 - die kleine hexe - ...,Die kleine hexe - das hörspiel,Various artists - topic,Kapitel 5.2 - hundeherz,0.0,0.0

### **Tracks Only Available on Spotify**

In [240]:
col=['Artist','Track','Album']

In [241]:
spotify_only=df[df['URL_youtube'].isnull()][col]

In [242]:
spotify_only

,Artist,Track,Album
410,Wisin & yandel,Besos moja2,La última misión
411,Wisin & yandel,Mayor que usted,Mayor que usted
412,Wisin & yandel,Vapor,La última misión
413,Wisin & yandel,Si te pillo,Si te pillo
414,Wisin & yandel,Noche de entierro,Mas flow - los benjamins
...,...,...,...
20090,Guilherme & benuto,Pulei na piscina - ao vivo,Drive-in (ao vivo)
20091,Guilherme & benuto,Batom vermelho,Batom vermelho
20092,Guilherme & benuto,Declaração pro bar - ao vivo,"Amando, bebendo e sofrendo (ao vivo) - ep 3"
20093,Fred again..,Rumble,Rumble
20282,Solfeggio healing frequencies mt,528 hz emotional healing,528 hz meditation music

### **Top 10 Most Streamed Tracks**

In [243]:
top_10_streams=df.nlargest(10,'Streams')[['Artist','Track','Album','Streams']]

In [244]:
top_10_streams

,Artist,Track,Album,Streams
15250,The weeknd,Blinding lights,After hours,3.386520e+09
12452,Ed sheeran,Shape of you,÷ (deluxe),3.362005e+09
19186,Lewis capaldi,Someone you loved,Divinely uninspired to a hellish extent,2.634013e+09
17937,Post malone,Rockstar (feat. 21 savage),Beerbongs & bentleys,2.594927e+09
17445,Swae lee,Sunflower - spider-man: into the spider-verse,Hollywood's bleeding,2.538330e+09
17938,Post malone,Sunflower - spider-man: into the spider-verse,Hollywood's bleeding,2.538330e+09
13503,Drake,One dance,Views,2.522432e+09
16028,Halsey,Closer,Closer,2.456205e+09
16099,The chainsmokers,Closer,Closer,2.456205e+09
14030,Imagine dragons,Believer,Evolve,2.369272e+09

### **Top 10 Most Viewed Videos**

In [245]:
top_10_viewed=df.nlargest(10,'Views')[['Artist','Title','Channel','Views']]

In [246]:
top_10_viewed

,Artist,Title,Channel,Views
1147,Luis fonsi,Luis fonsi - despacito ft. daddy yankee,Luisfonsivevo,8.079649e+09
365,Daddy yankee,Luis fonsi - despacito ft. daddy yankee,Luisfonsivevo,8.079647e+09
12452,Ed sheeran,Ed sheeran - shape of you (official music video),Ed sheeran,5.908398e+09
14580,Charlie puth,Wiz khalifa - see you again ft. charlie puth [...,Wiz khalifa music,5.773798e+09
12469,Wiz khalifa,Wiz khalifa - see you again ft. charlie puth [...,Wiz khalifa music,5.773797e+09
20303,Cocomelon,Wheels on the bus | cocomelon nursery rhymes &...,Cocomelon - nursery rhymes,4.898831e+09
10686,Mark ronson,Mark ronson - uptown funk (official video) ft....,Markronsonvevo,4.821016e+09
8937,Psy,Psy - gangnam style(강남스타일) m/v,Officialpsy,4.679767e+09
9569,Maroon 5,Maroon 5 - sugar (official music video),Maroon5vevo,3.817733e+09
13032,Katy perry,Katy perry - roar (official),Katyperryvevo,3.725749e+09

### **Videos with Highest Engagement Rate**

In [247]:
df['Engagement_rate']=(df['Likes']/df['Views'])*100

In [252]:
df['Engagement_rate']

0        0.896958
1        1.498547
2        3.344874
3        0.844645
4        1.002022
           ...
20713    1.552778
20714    1.225560
20715    0.922965
20716    1.347008
20717    1.565247
Name: Engagement_rate, Length: 20716, dtype: float64

In [251]:
df.nlargest(10,'Engagement_rate')[['Artist','Title','Channel','Views','Likes','Engagement_rate']]

,Artist,Title,Channel,Views,Likes,Engagement_rate
19968,J-hope,J-hope 'intro' visualizer,Bangtantv,954081.0,237761.0,24.920421
19969,J-hope,J-hope 'safety zone' visualizer,Bangtantv,1952637.0,453910.0,23.246000
19967,J-hope,J-hope 'future' visualizer,Bangtantv,1180522.0,250116.0,21.186899
19971,J-hope,J-hope 'pandora’s box' visualizer,Bangtantv,1265231.0,253702.0,20.051832
12193,Camila,Camila resistiré,Carmen justano,49.0,9.0,18.367347
16297,Galantis,Coldplay x bts - my universe (galantis remix) ...,Coldplay,2067753.0,371437.0,17.963316
15065,Max,Agust d (feat. max) - burn it (vfx clip),Max,1054438.0,188244.0,17.852543
8105,Rm,Rm 'no.2 (with 박지윤)' visualizer,Bangtantv,2050047.0,346440.0,16.899125
14564,Bts,[episode] bts (방탄소년단) ‘bad decisions’ recordin...,Bangtantv,4844158.0,775430.0,16.007529
8104,Rm,Rm 'hectic (with colde)' visualizer,Bangtantv,1910843.0,305506.0,15.988022

### **Views Vs Streams Correlation**
**corr=0.60 indicating moderate to stong relation**

In [253]:
df[['Views','Streams']].corr()

            Views   Streams
Views    1.000000  0.601905
Streams  0.601905  1.000000